projects:
  cove:
    schemaPath: amplify/backend/api/cove/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: ca-central-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
